import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LANGUAGES = {
  zh: {
    code: 'zh',
    name: '中文',
    flag: '🇨🇳'
  },
  en: {
    code: 'en', 
    name: 'English',
    flag: '🇺🇸'
  }
};

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState('zh');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('preferred-language');
    if (savedLanguage && LANGUAGES[savedLanguage]) {
      setCurrentLanguage(savedLanguage);
    } else {
      const browserLanguage = navigator.language.toLowerCase();
      if (browserLanguage.startsWith('en')) {
        setCurrentLanguage('en');
      } else {
        setCurrentLanguage('zh');
      }
    }
  }, []);

  const changeLanguage = (languageCode) => {
    if (LANGUAGES[languageCode]) {
      setCurrentLanguage(languageCode);
      localStorage.setItem('preferred-language', languageCode);
    }
  };

  const t = (key, variables = null, fallback = '') => {
    const translations = getTranslations(currentLanguage);
    let text = translations[key] || fallback;
    
    if (variables && typeof variables === 'object') {
      Object.keys(variables).forEach(varKey => {
        text = text.replace(new RegExp(`{${varKey}}`, 'g'), variables[varKey]);
      });
    }
    
    return text;
  };

  const value = {
    currentLanguage,
    changeLanguage,
    t,
    languages: LANGUAGES,
    isChineseLanguage: currentLanguage === 'zh',
    isEnglishLanguage: currentLanguage === 'en'
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

const getTranslations = (language) => {
  const translations = {
    zh: {
      'app.title': 'CSR志愿者匹配系统',
      'app.subtitle': '连接需要帮助的人与热心志愿者',
      'common.loading': '加载中...',
      'common.error': '错误',
      'common.success': '成功',
      'common.confirm': '确认',
      'common.cancel': '取消',
      'permission.denied': '访问被拒绝：仅限系统管理员',
      'common.save': '保存',
      'common.edit': '编辑',
      'common.delete': '删除',
      'common.view': '查看',
      'common.search': '搜索',
      'common.filter': '过滤',
      'common.clear': '清除',
      'common.submit': '提交',
      'common.back': '返回',
      'common.next': '下一步',
      'common.previous': '上一步',
      'common.close': '关闭',
      'common.unknown': '未知',
      'common.never': '从未',
      'common.all': '全部',
      'common.refresh': '刷新',
      'common.refreshing': '刷新中...',
      'common.generate': '生成',
      'common.download': '下载',
      'common.settings': '设置',
      'common.newUser': '新用户注册',
      'common.urgency': '紧急程度',
      'common.location': '地点',
      'common.createdAt': '创建时间',
      'common.volunteer': '志愿者',
      'common.newRequest': '新服务请求',
      'common.requestMatched': '请求已匹配',
      'common.locale': 'zh-CN',
      
      // 时间相关
      'time.justNow': '刚刚',
      'time.minutesAgo': '{count}分钟前',
      'time.hoursAgo': '{count}小时前',
      'time.daysAgo': '{count}天前',
      'time.weeksAgo': '{count}周前',
      'time.monthsAgo': '{count}个月前',
      'time.yearsAgo': '{count}年前',
      'time.updatedAt': '数据更新于',
      'time.createdAt': '创建于',
      'time.lastUpdate': '最后更新',
      
      // 导航
      'nav.logout': '退出',
      'nav.dashboard': '仪表板',
      'nav.profile': '个人资料',
      
      // PIN用户导航
      'nav.pin.dashboard': '我的请求',
      'nav.pin.history': '历史记录',
      
      // CSR用户导航  
      'nav.csr.search': '搜索机会',
      'nav.csr.shortlist': '收藏夹',
      'nav.csr.history': '服务历史',
      
      // 管理员导航
      'nav.admin.dashboard': '仪表板',
      'nav.admin.users': '用户管理',
      'nav.admin.categories': '类别管理',
      'nav.admin.reports': '数据报告',
      'nav.admin.systemLogs': '系统日志',
      'nav.admin.alerts': '系统警报',
      'nav.admin.performance': 'CSR绩效',
      'nav.viewProfile': '查看个人资料',

      // 个人资料页面
      'profile.editProfile': '编辑资料',
      'profile.basicInfo': '基本信息',
      'profile.name': '姓名',
      'profile.email': '邮箱',
      'profile.phone': '电话',
      'profile.address': '地址',
      'profile.emergencyInfo': '紧急联系信息',
      'profile.emergencyContact': '紧急联系人',
      'profile.emergencyContactPlaceholder': '姓名和电话',
      'profile.workInfo': '工作信息',
      'profile.organization': '所属机构',
      'profile.skills': '技能专长',
      'profile.accountInfo': '账户信息',
      'profile.userType': '用户类型',
      'profile.joinDate': '注册时间',
      'profile.lastUpdate': '最后更新',
      'profile.changeAvatar': '更换头像',
      'profile.avatarTooLarge': '头像文件大小不能超过2MB',
      'profile.invalidImageType': '请选择有效的图片文件',
      'profile.updateSuccess': '个人信息更新成功！',
      'profile.updateError': '更新失败，请重试',
      'profile.noName': '未设置姓名',

      // 技能选项
      'skills.medical': '医疗护理',
      'skills.transport': '交通出行',
      'skills.technology': '技术支持',
      'skills.education': '教育培训',
      'skills.household': '家务服务',
      'skills.companion': '陪伴关怀',
      
      // 管理员 - 类别管理
      'admin.categories.title': '服务类别管理',
      'admin.categories.subtitle': '管理系统中的服务类别',
      'admin.categories.addNew': '添加新类别',
      'admin.categories.placeholder': '输入新类别名称...',
      'admin.categories.add': '添加类别',
      'admin.categories.existing': '现有类别',
      'admin.categories.count': '个类别',
      'admin.categories.relatedRequests': '个相关请求',
      'admin.categories.clickToView': '点击查看相关请求',
      'admin.categories.clickHint': '点击查看',
      'admin.categories.viewRequests': '查看请求',
      'admin.categories.requestList': '请求列表',
      'admin.categories.totalRequests': '总请求数',
      'admin.categories.pendingRequests': '待处理',
      'admin.categories.matchedRequests': '已匹配',
      'admin.categories.noRequests': '暂无请求',
      'admin.categories.noRequestsDesc': '该类别下还没有任何请求',
      'admin.categories.viewDetail': '查看详情',
      'admin.categories.editRequest': '编辑请求',
      'admin.categories.freezeRequest': '冻结请求',
      'admin.categories.unfreezeRequest': '解冻请求',
      'admin.categories.deleteRequest': '删除请求',
      'admin.categories.requestDetail': '请求详情',
      'admin.categories.editRequestTitle': '编辑请求',
      'admin.categories.basicInfo': '基本信息',
      'admin.categories.requestTitle': '请求标题',
      'admin.categories.requestDescription': '详细描述',
      'admin.categories.requestStatus': '状态',
      'admin.categories.requestUrgency': '紧急程度',
      'admin.categories.requestCategory': '类别',
      'admin.categories.requestLocation': '地点',
      'admin.categories.requestCreated': '创建时间',
      'admin.categories.requestUpdated': '更新时间',
      'admin.categories.requestFrozen': '冻结时间',
      'admin.categories.volunteerInfo': '志愿者信息',
      'admin.categories.contactInfo': '联系信息',
      'admin.categories.requesterName': '申请人',
      'admin.categories.contactMethod': '联系方式',
      'admin.categories.saveChanges': '保存更改',
      'admin.categories.confirmDelete': '确定要删除这个请求吗？此操作无法撤销。',
      
      // 管理员 - 数据报告
      'admin.reports.title': '数据报告',
      'admin.reports.daily': '日报',
      'admin.reports.weekly': '周报',
      'admin.reports.monthly': '月报',
      'admin.reports.generate': '生成报告',
      'admin.reports.generating': '生成中...',
      'admin.reports.totalMatches': '总匹配数',
      'admin.reports.newUsers': '新注册用户',
      'admin.reports.activeRequests': '活跃请求',
      'admin.reports.completionRate': '完成率',
      'admin.reports.config': '报告配置',
      'admin.reports.reportType': '报告类型',
      'admin.reports.growthLastMonth': '较上月增长',
      'admin.reports.currentActive': '当前活跃',
      'admin.reports.periodCompletion': '周期完成率',
      'admin.reports.systemInfo': '系统信息',
      'admin.reports.timeRange': '时间范围',
      'admin.reports.generatedTime': '生成时间',
      'admin.reports.totalUsers': '总用户数',
      'admin.reports.totalRequests': '总请求数',
      'admin.reports.systemStatus': '系统状态',
      'admin.reports.statusGood': '良好',
      'admin.reports.statusNeedAttention': '需要关注',
      'dailyGrowth': '较昨日',
      'weeklyGrowth': '较上周',
      'monthlyGrowth': '较上月',
      'growth': '增长',
      'decrease': '下降',
      'reportPeriod': '报告周期',
      'generatedAt': '生成时间',
      'selectDate': '选择日期',
      'selectWeek': '选择周',
      'selectMonth': '选择月份',
      'weekHelp': '选择要查看的周',
      'monthHelp': '选择要查看的月份',
      'configDescription': '选择报告类型和时间范围来生成详细的数据分析报告',
      'admin.reports.systemDataAnalysis': '系统运行数据统计与分析',
      'admin.reports.download': '下载报告',
      'admin.reports.categoryBreakdown': '分类统计',
      'admin.reports.requests': '请求',
      'admin.reports.matched': '已匹配',
      'admin.reports.topPerformers': '优秀志愿者',
      'admin.reports.matches': '次匹配',
      'admin.reports.categories': '个分类',
      'admin.reports.dateRange': '时间范围',
      'admin.reports.systemHealth': '系统状态',
      'admin.reports.healthy': '良好',
      'admin.reports.needsAttention': '需要关注',
      'admin.reports.downloadError': '下载报告失败，请重试',
      
      // 管理员 - 系统日志
      'admin.systemLogs.title': '系统日志',
      'admin.systemLogs.subtitle': '查看和分析系统操作记录',
      'admin.systemLogs.totalLogs': '总日志数',
      'admin.systemLogs.successfulLogins': '成功登录',
      'admin.systemLogs.failedAttempts': '失败尝试',
      'admin.systemLogs.systemActions': '系统操作',
      'admin.systemLogs.allLogs': '全部日志',
      'admin.systemLogs.loginLogs': '登录日志',
      'admin.systemLogs.securityLogs': '安全日志',
      'admin.systemLogs.systemLogs': '系统日志',
      'admin.systemLogs.searchPlaceholder': '搜索用户、操作或详情...',
      'admin.systemLogs.noLogs': '暂无日志记录',
      'admin.systemLogs.noLogsDesc': '当前筛选条件下没有日志',
      'admin.systemLogs.time': '时间',
      'admin.systemLogs.type': '类型',
      'admin.systemLogs.action': '操作',
      'admin.systemLogs.user': '用户',
      'admin.systemLogs.status': '状态',
      'admin.systemLogs.ipAddress': 'IP地址',
      'admin.systemLogs.details': '详情',
      
      // 管理员 - 系统警报
      'admin.alerts.title': '系统警报配置',
      'admin.alerts.subtitle': '配置系统监控和通知规则',
      'admin.alerts.createNew': '创建新警报',
      'admin.alerts.totalAlerts': '总警报数',
      'admin.alerts.activeAlerts': '已启用',
      'admin.alerts.triggered': '今日触发',
      'admin.alerts.securityAlerts': '安全警报',
      'admin.alerts.noAlerts': '暂无警报配置',
      'admin.alerts.noAlertsDesc': '点击上方按钮创建新的警报规则',
      'admin.alerts.threshold': '阈值',
      'admin.alerts.recipients': '接收人',
      'admin.alerts.lastTriggered': '最后触发',
      'admin.alerts.triggerCount': '触发次数',
      'admin.alerts.notifyList': '通知列表',
      'admin.alerts.editAlert': '编辑警报',
      'admin.alerts.createAlert': '创建警报',
      'admin.alerts.comingSoon': '功能开发中',
      'admin.alerts.comingSoonDesc': '警报创建和编辑功能即将推出',
      'admin.alerts.confirmDelete': '确认删除此警报配置？',
      'admin.alerts.failedLoginAlert': '失败登录警报',
      'admin.alerts.failedLoginDesc': '当用户连续失败登录超过阈值时触发',
      'admin.alerts.systemResourceAlert': '系统资源警报',
      'admin.alerts.systemResourceDesc': '当系统内存使用率超过85%时触发',
      'admin.alerts.userSurgeAlert': '用户注册激增',
      'admin.alerts.userSurgeDesc': '当每小时注册用户超过50人时触发',
      'admin.alerts.dbConnectionAlert': '数据库连接失败',
      'admin.alerts.dbConnectionDesc': '数据库连接失败时立即触发',
      'admin.alerts.suspiciousIPAlert': '可疑IP活动',
      'admin.alerts.suspiciousIPDesc': '当同一IP在短时间内有异常请求时触发',
      'admin.alerts.typeSecurity': '安全',
      'admin.alerts.typeSystem': '系统',
      'admin.alerts.typeUser': '用户',
      'admin.alerts.people': '人',
      'admin.alerts.times': '次',
      
      // 管理员仪表板
      'admin.dashboard.welcome': '欢迎回来',
      'admin.dashboard.description': '系统管理与数据监控中心',
      'admin.dashboard.noRecentActivity': '暂无最近活动',
      
      // 报告页面新增翻译
      'reports': '数据报告',
      'systemDataAnalysis': '系统运行数据统计与分析',
      'reportConfiguration': '报告配置',
      'reportType': '报告类型',
      'dailyReport': '日报',
      'weeklyReport': '周报',
      'monthlyReport': '月报',
      'dateRange': '时间范围',
      'generateReport': '生成报告',
      'generating': '生成中...',
      'downloadReport': '下载报告',
      'totalMatches': '总匹配数',
      'newUsers': '新注册用户',
      'activeRequests': '活跃请求',
      'completionRate': '完成率',
      'monthlyGrowth': '较上月增长',
      'currentActive': '当前活跃',
      'periodCompletion': '周期完成率',
      'categoryBreakdown': '分类统计',
      'requests': '请求',
      'matched': '已匹配',
      'topPerformers': '优秀志愿者',
      'matches': '次匹配',
      'categories': '个分类',
      'systemInfo': '系统信息',
      'generatedAt': '生成时间',
      'totalUsers': '总用户数',
      'totalRequests': '总请求数',
      'systemHealth': '系统状态',
      'healthy': '良好',
      'needsAttention': '需要关注',
      
      // 管理员 - 仪表板
      'admin.dashboard.title': '管理员仪表板',
      'admin.dashboard.userManagement': '用户管理',
      'admin.dashboard.serviceCategories': '服务类别',
      'admin.dashboard.dataReports': '数据报告',
      'admin.dashboard.systemSettings': '系统设置',
      'admin.dashboard.systemLogs': '系统日志',
      'admin.dashboard.alerts': '系统警报',
      'admin.dashboard.participation': '参与度监控',
      'admin.dashboard.csrPerformance': 'CSR绩效',
      'admin.dashboard.exportReport': '导出报告',
      'admin.dashboard.quickActions': '快速操作',
      'admin.dashboard.recentActivity': '最近活动',
      'admin.dashboard.totalUsers': '总用户数',
      'admin.dashboard.activeRequests': '活跃请求',
      'admin.dashboard.todayMatches': '今日匹配',
      'admin.dashboard.pendingReview': '待审核',
      'admin.dashboard.thisMonth': '本月',
      'admin.dashboard.generateReport': '生成报告',
      'admin.dashboard.refreshData': '刷新数据',
      'admin.dashboard.noActivity': '暂无最近活动',
      'admin.dashboard.reportGenerated': '报告已生成并下载！',
      'admin.dashboard.reportError': '生成报告失败，请稍后再试。',
      
      // 管理员 - 用户管理
      'admin.users.title': '用户管理',
      'admin.users.subtitle': '管理系统中的所有用户账户',
      'admin.users.totalUsers': '总用户数',
      'admin.users.users': '用户',
      'admin.users.searchPlaceholder': '搜索用户姓名或邮箱...',
      'admin.users.allUsers': '所有用户',
      'admin.users.name': '姓名',
      'admin.users.email': '邮箱',
      'admin.users.userType': '用户类型',
      'admin.users.status': '状态',
      'admin.users.requestCount': '请求数量',
      'admin.users.joinDate': '注册日期',
      'admin.users.lastLogin': '最后登录',
      'admin.users.actions': '操作',
      'admin.users.active': '活跃',
      'admin.users.suspended': '已暂停',
      'admin.users.view': '查看',
      'admin.users.suspend': '暂停',
      'admin.users.activate': '激活',
      'admin.users.delete': '删除',
      'admin.users.confirmDelete': '确定要删除这个用户吗？此操作无法撤销。',
      'admin.users.confirmDeleteWithRequests': '该用户有 {count} 个相关请求，删除用户将同时删除这些请求。',
      'admin.users.deleteSuccess': '用户已成功删除',
      'admin.users.deleteSuccessWithRequests': '已成功删除 {userCount} 个用户和 {requestCount} 个相关请求',
      'admin.users.noUsers': '没有找到用户',
      'admin.users.noUsersDesc': '当前筛选条件下没有用户',
      'admin.users.userDetails': '用户详情',
      'admin.users.phone': '电话',
      'admin.users.address': '地址',
      'admin.users.emergencyContact': '紧急联系人',
      'admin.users.organization': '组织机构',
      'admin.users.skills': '技能',
      
      // 登录页面
      'auth.login.title': '欢迎回来',
      'auth.login.subtitle': '请登录您的账户',
      'auth.login.email': '邮箱地址',
      'auth.login.password': '密码',
      'auth.login.userType': '选择身份',
      'auth.login.submit': '登录',
      'auth.login.register': '还没有账户？立即注册',
      'auth.login.noAccount': '还没有账户？',
      'auth.login.registerNow': '立即注册',
      'auth.login.adminLogin': '管理员登录',
      'auth.login.adminLoginDesc': '您正在使用管理员账户登录，无需选择用户类型',
      'auth.login.error.userType': '请选择用户类型',
      'auth.login.error.userNotExists': '用户不存在，请先注册',
      'auth.login.error.userSuspended': '您的账户已被暂停，请联系管理员',
      'auth.register.error.emailExists': '该邮箱已被注册',
      'auth.register.error.userType': '请选择用户类型',
      'auth.register.error.passwordMismatch': '密码确认不匹配',
      'auth.register.error.passwordTooShort': '密码至少需要6位',
      'auth.register.error.requiredFields': '请填写所有必填信息',
      
      // 用户类型
      'userType.pin': '需要帮助者 (PIN)',
      'userType.pin.description': '寻求志愿服务帮助',
      'userType.csr': '志愿者 (CSR)',
      'userType.csr.description': '提供志愿服务',
      'userType.admin': '平台管理员',
      'userType.admin.description': '管理系统运营',
      
      // PIN Dashboard
      'pin.dashboard.title': '我的仪表板',
      'pin.dashboard.welcome': '欢迎回来，{name}！',
      'pin.dashboard.createRequest': '创建新请求',
      'pin.dashboard.myRequests': '我的请求列表',
      'pin.dashboard.manageRequests': '管理您的所有求助请求',
      'pin.dashboard.quickActions': '快速操作',
      'pin.dashboard.viewHistory': '查看历史',
      'pin.dashboard.getHelp': '使用帮助',
      'pin.dashboard.noRequests': '还没有请求',
      'pin.dashboard.noRequestsDesc': '发布您的第一个求助请求，寻找热心的志愿者',
      'pin.dashboard.createFirst': '发布您的第一个求助请求，寻找热心的志愿者',
      'pin.dashboard.createMyFirst': '创建我的第一个请求',
      'pin.dashboard.createNew': '创建新请求',
      'pin.dashboard.help': '使用帮助',
      'pin.dashboard.viewDetails': '查看详情',
      'pin.dashboard.edit': '编辑',
      'pin.dashboard.delete': '删除',
      'pin.dashboard.matchedVolunteer': '匹配志愿者：{name}',
      'pin.dashboard.contactVolunteer': '点击联系志愿者',
      'pin.dashboard.status.matched': '已匹配',
      'pin.dashboard.status.waiting': '等待中',
      'pin.dashboard.status.pending': '待处理',
      'pin.dashboard.status.processing': '处理中',
      
      // PIN Dashboard - 新设计翻译
      'pin.dashboard.welcomeBack': '欢迎回来',
      'pin.dashboard.hello': '你好',
      'pin.dashboard.heroSubtitle': '管理您的请求，连接热心志愿者，创造美好改变',
      'pin.dashboard.viewAnalytics': '查看分析',
      'pin.dashboard.yourImpact': '您的影响力',
      'pin.dashboard.impactSubtitle': '看看您的请求如何帮助建设更好的社区',
      'pin.dashboard.stat.total.description': '您创建的总请求数量',
      'pin.dashboard.stat.matched.description': '已成功匹配志愿者的请求',
      'pin.dashboard.stat.pending.description': '正在等待志愿者响应的请求',
      'pin.dashboard.stat.views.description': '所有请求的累计浏览次数',
      'pin.dashboard.manageYourRequests': '管理您的所有求助请求',
      'pin.dashboard.noRequestsYet': '还没有创建任何请求',
      'pin.dashboard.createFirstRequest': '创建您的第一个求助请求，开始寻找热心的志愿者帮助您',
      'pin.dashboard.getStarted': '开始创建',
      'pin.dashboard.newRequest': '新请求',
      'pin.dashboard.createNewRequest': '创建新的求助请求',
      'pin.dashboard.history': '历史记录',
      'pin.dashboard.tips': '实用提示',
      'pin.dashboard.tip1': '详细描述您的需求可以帮助找到更合适的志愿者',
      'pin.dashboard.tip2': '添加图片可以让您的请求更加清晰明了',
      'pin.dashboard.tip3': '保持联系方式准确，方便志愿者联系您',
      'pin.dashboard.matchedWith': '已匹配志愿者：{name}',
      'pin.dashboard.contact': '联系',
      'pin.dashboard.applicants': '申请者',
      'pin.dashboard.interestedVolunteers': '申请的志愿者',
      'pin.dashboard.selectVolunteer': '选择',
      'pin.dashboard.confirmSelect': '确定选择这位志愿者吗？',
      'pin.dashboard.selectSuccess': '已成功匹配志愿者！',
      'pin.dashboard.complete': '完成',
      'pin.dashboard.confirmComplete': '确认已完成此请求吗？',
      'pin.dashboard.completeSuccess': '请求已完成！感谢您的评价。',
      'pin.dashboard.rateVolunteer': '评价志愿者',
      'pin.dashboard.serviceRating': '服务评分',
      'pin.dashboard.feedback': '评价反馈',
      'pin.dashboard.feedbackPlaceholder': '分享您对志愿者服务的评价和建议...',
      'pin.dashboard.submitRating': '提交评价',
      'pin.dashboard.filterByStatus': '按状态筛选',
      'pin.dashboard.sortBy': '排序方式',
      'pin.dashboard.sort.newest': '最新创建',
      'pin.dashboard.sort.oldest': '最早创建',
      'pin.dashboard.sort.urgent': '按紧急程度',
      'pin.dashboard.showing': '显示',
      'pin.dashboard.status.completed': '已完成',
      'rating.poor': '很差',
      'rating.fair': '一般',
      'rating.good': '良好',
      'rating.veryGood': '很好',
      'rating.excellent': '优秀',
      'common.optional': '可选',
      'common.online': '在线',
      'common.total': '总计',
      'common.views': '浏览',
      'common.shortlisted': '收藏',
      'common.volunteers': '名志愿者',
      'common.new': '新增',
      'common.saved': '已保存',
      'common.urgent': '紧急',
      'common.help': '帮助',
      'common.allCategories': '所有分类',
      'common.high': '高',
      'common.medium': '中',
      'common.low': '低',
      
      // CSR Dashboard - 新设计翻译
      'csr.dashboard.welcomeVolunteer': '欢迎志愿者',
      'csr.dashboard.hello': '你好',
      'csr.dashboard.heroSubtitle': '发现志愿服务机会，帮助需要帮助的人，传播爱心',
      'csr.dashboard.exploreRequests': '探索请求',
      'csr.dashboard.myShortlist': '我的收藏',
      'csr.dashboard.topVolunteer': '优秀志愿者',
      'csr.dashboard.thisMonth': '本月',
      'csr.dashboard.communityOverview': '社区概览',
      'csr.dashboard.overviewSubtitle': '了解社区需求，找到您可以帮助的机会',
      'csr.dashboard.totalRequests': '总请求数',
      'csr.dashboard.totalRequestsDesc': '社区中所有待帮助的请求',
      'csr.dashboard.newToday': '今日新增',
      'csr.dashboard.newTodayDesc': '今天新发布的求助请求',
      'csr.dashboard.shortlistDesc': '您关注和收藏的请求',
      'csr.dashboard.urgentRequests': '紧急请求',
      'csr.dashboard.urgentDesc': '需要立即关注的紧急求助',
      'csr.dashboard.recentRequests': '最新请求',
      'csr.dashboard.latestHelpRequests': '查看最新发布的求助请求',
      'csr.dashboard.volunteer': '我要帮助',
      'csr.dashboard.noCategoryRequests': '此分类暂无请求',
      'csr.dashboard.tryDifferentCategory': '试试其他分类或稍后再来查看',
      'csr.dashboard.noRecentRequests': '暂无最新请求',
      'csr.dashboard.checkBackLater': '请稍后再来查看新的求助请求',
      'csr.dashboard.exploreAll': '探索所有请求',
      'csr.dashboard.quickActions': '快速操作',
      'csr.dashboard.searchRequests': '搜索请求',
      'csr.dashboard.findOpportunities': '寻找志愿服务机会',
      'csr.dashboard.viewShortlist': '查看收藏',
      'csr.dashboard.savedRequests': '您保存的请求',
      'csr.dashboard.myHistory': '我的历史',
      'csr.dashboard.pastActivities': '过往志愿活动',
      'csr.dashboard.getSupport': '获取帮助支持',
      'csr.dashboard.yourImpact': '您的影响力',
      'csr.dashboard.helpedPeople': '帮助的人',
      'csr.dashboard.hoursVolunteered': '志愿时长',
      'csr.dashboard.satisfaction': '满意度',
      'csr.dashboard.impactMessage': '感谢您的无私奉献！您的每一次帮助都在让世界变得更美好。',
      'common.viewDetails': '查看详情',
      
      // PIN历史记录
      'pin.history.title': '历史匹配记录',
      'pin.history.allServiceTypes': '所有服务类型',
      'pin.history.medical': '医疗',
      'pin.history.transport': '交通',
      'pin.history.applyFilters': '应用筛选',
      
      // 统计
      'stats.totalRequests': '总请求数',
      'stats.matched': '已匹配',
      'stats.pending': '等待匹配',
      'stats.totalViews': '总浏览量',
      'stats.availableOpportunities': '可用机会',
      'stats.urgentRequests': '紧急请求',
      
      // CSR搜索页面
      'csr.search.title': '搜索志愿机会',
      'csr.search.subtitle': '寻找您可以参与的志愿服务机会，帮助有需要的人',
      'csr.search.searchPlaceholder': '搜索请求标题、描述或地点...',
      'csr.search.allCategories': '所有分类',
      'csr.search.allUrgency': '所有紧急程度',
      'csr.search.opportunities': '志愿服务机会',
      'csr.search.opportunitiesDesc': '点击"申请志愿"来帮助有需要的人',
      'csr.search.applyVolunteer': '申请志愿',
      'csr.search.applied': '已申请',
      'csr.search.viewDetails': '查看详情',
      'csr.search.noOpportunities': '暂无志愿机会',
      'csr.search.noOpportunitiesDesc': '目前没有待匹配的志愿服务请求，请稍后再查看',
      'csr.search.noResults': '没有匹配的结果',
      'csr.search.noResultsDesc': '尝试调整搜索条件或清除过滤器',
      'csr.search.clearFilters': '清除过滤器',
      'csr.search.confirmApply': '确定要申请这个志愿服务机会吗？',
      'csr.search.applySuccess': '申请成功！您可以在历史记录中查看您的志愿服务记录。',
      'csr.search.loginRequired': '请先登录后再申请志愿服务！',
      'csr.search.applyError': '申请失败，请重试！',
      'csr.search.cancelApplication': '取消申请',
      'csr.search.confirmCancel': '确认取消申请？',
      'csr.search.cancelSuccess': '已取消申请',
      'csr.search.cancelError': '取消申请失败，请重试！',
      'csr.search.rejectRequest': '拒绝请求',
      'csr.search.rejectReason': '拒绝原因',
      'csr.search.rejectReasonPlaceholder': '请说明该请求为何不在您的职责范围内...',
      'csr.search.confirmReject': '确认拒绝该请求？此操作将隐藏该请求。',
      'csr.search.rejectSuccess': '已拒绝该请求',
      'csr.search.rejectError': '拒绝失败，请重试！',
      'csr.search.shortlist': '收藏',
      'csr.search.shortlisted': '已收藏',
      'csr.search.addToShortlist': '已添加到收藏夹',
      'csr.search.removeFromShortlist': '已从收藏夹移除',
      
      // CSR历史记录
      'csr.history.title': '志愿服务历史',
      'csr.history.subtitle': '查看您完成的志愿服务记录和帮助历史',
      'csr.history.totalServices': '完成服务',
      'csr.history.serviceTypes': '服务类型',
      'csr.history.mostActive': '最常服务',
      'csr.history.filterByType': '服务类型',
      'csr.history.allServiceTypes': '所有服务类型',
      'csr.history.startDate': '开始日期',
      'csr.history.endDate': '结束日期',
      'csr.history.clearFilters': '清除过滤器',
      'csr.history.resultsFound': '找到 {count} 条服务记录',
      'csr.history.noRecords': '暂无服务记录',
      'csr.history.noRecordsDesc': '您还没有完成任何志愿服务。去搜索页面找到需要帮助的人，开始您的志愿服务之旅！',
      'csr.history.noFilteredRecords': '没有符合条件的记录',
      'csr.history.noFilteredRecordsDesc': '尝试调整过滤条件查看更多记录',
      'csr.history.browseOpportunities': '浏览志愿机会',
      'csr.history.serviceDate': '服务时间',
      'csr.history.serviceObject': '服务对象',
      'csr.history.serviceLocation': '服务地点',
      'csr.history.expectedTime': '预期时间',
      'csr.history.contactInfo': '联系方式',
      'csr.history.toBeConfirmed': '待确定',
      'csr.history.unknown': '未知',
      
      // CSR收藏夹
      'csr.shortlist.title': '我的收藏夹',
      
      // 帮助页面
      'help.title': '使用帮助',
      'help.subtitle': '了解如何使用CSR志愿者匹配系统，获取最佳体验',
      
      // PIN用户帮助
      'help.pin.title': '需要帮助者 (PIN) 使用指南',
      'help.pin.createRequest.title': '如何创建求助请求',
      'help.pin.createRequest.description': '发布您的求助请求，让志愿者找到您',
      'help.pin.createRequest.step1': '点击"创建新请求"按钮',
      'help.pin.createRequest.step2': '填写详细的请求信息和需求描述',
      'help.pin.createRequest.step3': '选择合适的服务类别和紧急程度',
      'help.pin.createRequest.step4': '提交请求等待志愿者申请',
      'help.pin.manageRequests.title': '管理我的请求',
      'help.pin.manageRequests.description': '查看、编辑和管理您的所有求助请求',
      'help.pin.manageRequests.step1': '在仪表板查看所有请求状态',
      'help.pin.manageRequests.step2': '点击"编辑"修改请求信息',
      'help.pin.manageRequests.step3': '查看志愿者申请和联系信息',
      
      // CSR用户帮助
      'help.csr.title': '志愿者 (CSR) 使用指南',
      'help.csr.searchOpportunities.title': '搜索志愿机会',
      'help.csr.searchOpportunities.description': '找到您可以参与的志愿服务机会',
      'help.csr.searchOpportunities.step1': '使用搜索栏和过滤器找到合适的机会',
      'help.csr.searchOpportunities.step2': '查看请求详情了解具体需求',
      'help.csr.searchOpportunities.step3': '将感兴趣的机会添加到收藏夹',
      'help.csr.applyVolunteer.title': '申请志愿服务',
      'help.csr.applyVolunteer.description': '申请参与志愿服务并与需要帮助的人联系',
      'help.csr.applyVolunteer.step1': '点击"申请志愿"按钮',
      'help.csr.applyVolunteer.step2': '确认申请信息并提交',
      'help.csr.applyVolunteer.step3': '等待匹配成功后联系求助者',
      
      // 管理员帮助
      'help.admin.title': '管理员使用指南',
      'help.admin.categoryManagement.title': '管理服务类别',
      'help.admin.categoryManagement.description': '添加、编辑和删除系统中的服务类别',
      'help.admin.categoryManagement.step1': '在类别管理页面查看现有类别',
      'help.admin.categoryManagement.step2': '添加新的服务类别',
      'help.admin.categoryManagement.step3': '删除不再需要的类别',
      'help.admin.reports.title': '查看数据报告',
      'help.admin.reports.description': '生成和查看系统使用统计报告',
      'help.admin.reports.step1': '选择报告类型（日报、周报、月报）',
      'help.admin.reports.step2': '点击生成报告按钮',
      'help.admin.reports.step3': '分析用户活动和匹配数据',
      
      // 常见问题
      'help.faq.title': '常见问题',
      'help.faq.q1.question': '如何创建一个有效的求助请求？',
      'help.faq.q1.answer': '请详细描述您的需求，包括具体的时间、地点和期望的帮助类型。清晰的描述有助于志愿者更好地理解您的需求。',
      'help.faq.q2.question': '志愿者申请后多久能得到回复？',
      'help.faq.q2.answer': '通常在24小时内，求助者会查看志愿者申请并做出回应。系统会自动发送通知提醒。',
      'help.faq.q3.question': '如何修改已发布的请求？',
      'help.faq.q3.answer': '在您的仪表板中找到相应请求，点击"编辑"按钮即可修改请求信息。注意：已匹配的请求修改可能会影响志愿者。',
      'help.faq.q4.question': '系统是否收费？',
      'help.faq.q4.answer': 'CSR志愿者匹配系统完全免费。我们致力于为社区提供无偿的志愿服务匹配平台。',
      
      // 联系我们
      'help.contact.title': '联系我们',
      'help.contact.support.title': '技术支持',
      'help.contact.support.description': '遇到技术问题或需要使用帮助？',
      'help.contact.support.hours': '周一至周五 9:00-18:00',
      'help.contact.feedback.title': '意见反馈',
      'help.contact.feedback.description': '您的建议对我们很重要',
      'help.contact.feedback.form': '在线反馈表单',
      
      // 分类
      'category.medical': '医疗陪同',
      'category.transportation': '出行交通',
      'category.shopping': '购物协助',
      'category.household': '家务帮助',  
      'category.companion': '陪伴服务',
      'category.technology': '技术支持',
      'category.education': '教育辅导',
      'category.other': '其他',
      
      // 紧急程度
      'urgency.low': '低',
      'urgency.medium': '中',
      'urgency.high': '高',
      'urgency.urgent': '紧急',
      
      // 状态
      'status.pending': '等待中',
      'status.matched': '已匹配',
      'status.completed': '已完成',
      'status.cancelled': '已取消',
      
      // 请求表单
      'request.form.title': '请求标题',
      'request.form.category': '服务类型',
      'request.form.description': '详细描述',
      'request.form.location': '地点',
      'request.form.urgency': '紧急程度',
      'request.form.expectedDate': '预期日期',
      'request.form.expectedTime': '预期时间',
      'request.form.volunteersNeeded': '需要志愿者数量',
      'request.form.contactMethod': '联系方式',
      'request.form.additionalNotes': '备注信息',
      'request.form.attachments': '附件（可选）',
      'request.form.attachmentsHint': '支持图片、PDF、DOC/DOCX，单个文件大小上限5MB',
  'contact.phone': '电话',
  'contact.email': '邮箱',
  'contact.both': '电话和邮箱',
      'request.form.create': '创建新的求助请求',
      'request.form.edit': '编辑求助请求',
      'request.form.update': '更新请求',
  'request.form.titlePlaceholder': '请用至少5个字符简要描述您的需求',
  'request.validation.titleMinHint': '至少5个字符',
  'request.validation.descriptionMinHint': '至少10个字符',
  'request.form.descriptionPlaceholder': '请用至少10个字符详细描述您的需求，包括具体要求、注意事项等',
  'request.form.locationPlaceholder': '详细地址或区域',
  'request.form.additionalNotesPlaceholder': '任何其他需要说明的信息...',
  'request.form.submitting': '发布中...',
  'request.section.basicInfo': '基本信息',
  'request.section.timing': '时间安排与其他要求',
      
      // 请求详情
      'request.detail.title': '请求详情',
      'request.detail.basicInfo': '基本信息',
      'request.detail.description': '详细描述',
      'request.detail.timing': '时间信息',
      'request.detail.requester': '请求者信息',
      'request.detail.statistics': '统计数据',
      'request.detail.volunteer': '志愿者信息',
      'request.detail.createdAt': '创建时间',
      'request.detail.expectedTiming': '预期时间',
  'request.rating.leaveRatingFor': '为 {name} 留下评分',
  'request.rating.select': '选择评分',
  'request.rating.submit': '提交评分',
  'request.rating.feedbackPlaceholder': '可选：写下对志愿者的感谢或建议',
  'error.submitRating': '提交评分失败，请稍后再试',
  'error.updateRequestFailed': '更新请求失败',
  'error.deleteRequestFailed': '删除请求失败',
  'error.selectVolunteerFailed': '选择志愿者失败，请重试',
  'error.completeRequestFailed': '完成请求失败，请重试',
      'request.detail.viewCount': '浏览次数',
      'request.detail.shortlistCount': '收藏次数',
      'request.detail.matchedAt': '匹配时间',
      'request.detail.noVolunteer': '暂无匹配志愿者',
      
      // 时间
      'time.justNow': '刚刚',
      'time.hoursAgo': '{count}小时前',
      'time.daysAgo': '{count}天前',
      'time.weeksAgo': '{count}周前',
  'time.morning': '上午',
  'time.afternoon': '下午',
  'time.evening': '晚上',
    },
    
    en: {
      // Common
      'app.title': 'CSR Volunteer Matching System',
      'app.subtitle': 'Connecting people in need with caring volunteers',
      'common.loading': 'Loading...',
      'common.error': 'Error',
      'common.success': 'Success',
      'common.confirm': 'Confirm',
      'common.cancel': 'Cancel',
      'permission.denied': 'Access Denied: System Admin only',
      'common.save': 'Save',
      'common.edit': 'Edit',
      'common.delete': 'Delete',
      'common.view': 'View',
      'common.search': 'Search',
      'common.filter': 'Filter',
      'common.clear': 'Clear',
      'common.submit': 'Submit',
      'common.back': 'Back',
      'common.next': 'Next',
      'common.previous': 'Previous',
      'common.close': 'Close',
      'common.unknown': 'Unknown',
      'common.never': 'Never',
      'common.all': 'All',
      'common.refresh': 'Refresh',
      'common.refreshing': 'Refreshing...',
      'common.generate': 'Generate',
      'common.download': 'Download',
      'common.settings': 'Settings',
      'common.newUser': 'New user registered',
      'common.newRequest': 'New service request',
      'common.requestMatched': 'request matched',
      'common.urgency': 'Urgency',
      'common.location': 'Location',
      'common.createdAt': 'Created At',
      'common.volunteer': 'Volunteer',
      'common.locale': 'en-US',
      
      // Time Related
      'time.justNow': 'Just now',
      'time.minutesAgo': '{count} minutes ago',
      'time.hoursAgo': '{count} hours ago',
  'time.morning': 'Morning',
  'time.afternoon': 'Afternoon',
  'time.evening': 'Evening',
      'time.daysAgo': '{count} days ago',
      'time.weeksAgo': '{count} weeks ago',
      'time.monthsAgo': '{count} months ago',
      'time.yearsAgo': '{count} years ago',
      'time.updatedAt': 'Data updated at',
      'time.createdAt': 'Created at',
      'time.lastUpdate': 'Last update',
      
      // Navigation
      'nav.logout': 'Logout',
      'nav.dashboard': 'Dashboard',
      'nav.profile': 'Profile',
      
      // PIN Navigation
      'nav.pin.dashboard': 'My Requests',
      'nav.pin.history': 'History',
      
      // CSR Navigation
      'nav.csr.search': 'Search Opportunities',
      'nav.csr.shortlist': 'Shortlist',
      'nav.csr.history': 'Service History',
      
      // Admin Navigation
      'nav.admin.dashboard': 'Dashboard',
      'nav.admin.users': 'User Management',
      'nav.admin.categories': 'Category Management',
      'nav.admin.reports': 'Data Reports',
      'nav.admin.systemLogs': 'System Logs',
      'nav.admin.alerts': 'System Alerts',
      'nav.admin.performance': 'CSR Performance',
      'nav.viewProfile': 'View Profile',

      // Profile Page
      'profile.editProfile': 'Edit Profile',
      'profile.basicInfo': 'Basic Information',
      'profile.name': 'Name',
      'profile.email': 'Email',
      'profile.phone': 'Phone',
      'profile.address': 'Address',
      'profile.emergencyInfo': 'Emergency Contact Information',
      'profile.emergencyContact': 'Emergency Contact',
      'profile.emergencyContactPlaceholder': 'Name and phone number',
      'profile.workInfo': 'Work Information',
      'profile.organization': 'Organization',
      'profile.skills': 'Skills & Expertise',
      'profile.accountInfo': 'Account Information',
      'profile.userType': 'User Type',
      'profile.joinDate': 'Join Date',
      'profile.lastUpdate': 'Last Updated',
      'profile.changeAvatar': 'Change Avatar',
      'profile.avatarTooLarge': 'Avatar file size cannot exceed 2MB',
      'profile.invalidImageType': 'Please select a valid image file',
      'profile.updateSuccess': 'Profile updated successfully!',
      'profile.updateError': 'Update failed, please try again',
      'profile.noName': 'No name set',

      // Skills Options
      'skills.medical': 'Medical Care',
      'skills.transport': 'Transportation',
      'skills.technology': 'Technical Support',
      'skills.education': 'Education & Training',
      'skills.household': 'Household Services',
      'skills.companion': 'Companionship',
      
      // Admin - Category Management
      'admin.categories.title': 'Service Category Management',
      'admin.categories.subtitle': 'Manage service categories in the system',
      'admin.categories.addNew': 'Add New Category',
      'admin.categories.placeholder': 'Enter new category name...',
      'admin.categories.add': 'Add Category',
      'admin.categories.existing': 'Existing Categories',
      'admin.categories.count': 'categories',
      'admin.categories.relatedRequests': 'related requests',
      'admin.categories.clickToView': 'Click to view related requests',
      'admin.categories.clickHint': 'click to view',
      'admin.categories.viewRequests': 'View Requests',
      'admin.categories.requestList': 'Request List',
      'admin.categories.totalRequests': 'Total Requests',
      'admin.categories.pendingRequests': 'Pending',
      'admin.categories.matchedRequests': 'Matched',
      'admin.categories.noRequests': 'No Requests',
      'admin.categories.noRequestsDesc': 'No requests found in this category',
      'admin.categories.viewDetail': 'View Details',
      'admin.categories.editRequest': 'Edit Request',
      'admin.categories.freezeRequest': 'Freeze Request',
      'admin.categories.unfreezeRequest': 'Unfreeze Request',
      'admin.categories.deleteRequest': 'Delete Request',
      'admin.categories.requestDetail': 'Request Details',
      'admin.categories.editRequestTitle': 'Edit Request',
      'admin.categories.basicInfo': 'Basic Information',
      'admin.categories.requestTitle': 'Request Title',
      'admin.categories.requestDescription': 'Description',
      'admin.categories.requestStatus': 'Status',
      'admin.categories.requestUrgency': 'Urgency',
      'admin.categories.requestCategory': 'Category',
      'admin.categories.requestLocation': 'Location',
      'admin.categories.requestCreated': 'Created',
      'admin.categories.requestUpdated': 'Updated',
      'admin.categories.requestFrozen': 'Frozen',
      'admin.categories.volunteerInfo': 'Volunteer Information',
      'admin.categories.contactInfo': 'Contact Information',
      'admin.categories.requesterName': 'Requester',
      'admin.categories.contactMethod': 'Contact Method',
      'admin.categories.saveChanges': 'Save Changes',
      'admin.categories.confirmDelete': 'Are you sure you want to delete this request? This action cannot be undone.',
      
      // Admin - Data Reports
      'admin.reports.title': 'Data Reports',
      'admin.reports.daily': 'Daily Report',
      'admin.reports.weekly': 'Weekly Report',
      'admin.reports.monthly': 'Monthly Report',
      'admin.reports.generate': 'Generate Report',
      'admin.reports.generating': 'Generating...',
      'admin.reports.totalMatches': 'Total Matches',
      'admin.reports.newUsers': 'New Users',
      'admin.reports.activeRequests': 'Active Requests',
      'admin.reports.completionRate': 'Completion Rate',
      'admin.reports.config': 'Report Configuration',
      'admin.reports.reportType': 'Report Type',
      'admin.reports.growthLastMonth': 'Growth vs Last Month',
      'admin.reports.currentActive': 'Currently Active',
      'admin.reports.periodCompletion': 'Period Completion Rate',
      'admin.reports.systemInfo': 'System Information',
      'admin.reports.timeRange': 'Time Range',
      'admin.reports.generatedTime': 'Generated Time',
      'admin.reports.totalUsers': 'Total Users',
      'admin.reports.totalRequests': 'Total Requests',
      'admin.reports.systemStatus': 'System Status',
      'admin.reports.statusGood': 'Good',
      'admin.reports.statusNeedAttention': 'Need Attention',
      'dailyGrowth': 'vs Yesterday',
      'weeklyGrowth': 'vs Last Week',
      'monthlyGrowth': 'vs Last Month',
      'growth': 'Growth',
      'decrease': 'Decrease',
      'reportPeriod': 'Report Period',
      'generatedAt': 'Generated At',
      'selectDate': 'Select Date',
      'selectWeek': 'Select Week',
      'selectMonth': 'Select Month',
      'weekHelp': 'Select the week to view',
      'monthHelp': 'Select the month to view',
      'configDescription': 'Select report type and time range to generate detailed data analysis report',
      'admin.reports.systemDataAnalysis': 'System Operation Data Statistics and Analysis',
      'admin.reports.download': 'Download Report',
      'admin.reports.categoryBreakdown': 'Category Statistics',
      'admin.reports.requests': 'Requests',
      'admin.reports.matched': 'Matched',
      'admin.reports.topPerformers': 'Top Volunteers',
      'admin.reports.matches': 'Matches',
      'admin.reports.categories': 'Categories',
      'admin.reports.dateRange': 'Date Range',
      'admin.reports.systemHealth': 'System Health',
      'admin.reports.healthy': 'Healthy',
      'admin.reports.needsAttention': 'Needs Attention',
      'admin.reports.downloadError': 'Failed to download report, please try again',
      'growth': 'increase',
      'decrease': 'decrease',
      'reportPeriod': 'Report Period',
      'generatedAt': 'Generated At',
      'selectDate': 'Select Date',
      'selectWeek': 'Select Week',
      'selectMonth': 'Select Month',
      'weekHelp': 'Select the week to view',
      'monthHelp': 'Select the month to view',
      'configDescription': 'Select report type and time range to generate detailed data analysis reports',
      
      // Admin Dashboard
      'admin.dashboard.welcome': 'Welcome back',
      'admin.dashboard.description': 'System management and data monitoring center',
      'admin.dashboard.noRecentActivity': 'No recent activity',
      
      // Report page new translations
      'reports': 'Data Reports',
      'systemDataAnalysis': 'System data statistics and analysis',
      'reportConfiguration': 'Report Configuration',
      'reportType': 'Report Type',
      'dailyReport': 'Daily Report',
      'weeklyReport': 'Weekly Report',
      'monthlyReport': 'Monthly Report',
      'dateRange': 'Date Range',
      'generateReport': 'Generate Report',
      'generating': 'Generating...',
      'downloadReport': 'Download Report',
      'totalMatches': 'Total Matches',
      'newUsers': 'New Users',
      'activeRequests': 'Active Requests',
      'completionRate': 'Completion Rate',
      'monthlyGrowth': 'Monthly growth',
      'currentActive': 'Currently active',
      'periodCompletion': 'Period completion rate',
      'categoryBreakdown': 'Category Statistics',
      'requests': 'requests',
      'matched': 'matched',
      'topPerformers': 'Top Performers',
      'matches': 'matches',
      'categories': 'categories',
      'systemInfo': 'System Information',
      'generatedAt': 'Generated at',
      'totalUsers': 'Total Users',
      'totalRequests': 'Total Requests',
      'systemHealth': 'System Health',
      'healthy': 'Healthy',
      'needsAttention': 'Needs Attention',
      
      // Admin - System Logs
      'admin.systemLogs.title': 'System Logs',
      'admin.systemLogs.subtitle': 'View and analyze system operation records',
      'admin.systemLogs.totalLogs': 'Total Logs',
      'admin.systemLogs.successfulLogins': 'Successful Logins',
      'admin.systemLogs.failedAttempts': 'Failed Attempts',
      'admin.systemLogs.systemActions': 'System Actions',
      'admin.systemLogs.allLogs': 'All Logs',
      'admin.systemLogs.loginLogs': 'Login Logs',
      'admin.systemLogs.securityLogs': 'Security Logs',
      'admin.systemLogs.systemLogs': 'System Logs',
      'admin.systemLogs.searchPlaceholder': 'Search user, action or details...',
      'admin.systemLogs.noLogs': 'No logs found',
      'admin.systemLogs.noLogsDesc': 'No logs match the current filter',
      'admin.systemLogs.time': 'Time',
      'admin.systemLogs.type': 'Type',
      'admin.systemLogs.action': 'Action',
      'admin.systemLogs.user': 'User',
      'admin.systemLogs.status': 'Status',
      'admin.systemLogs.ipAddress': 'IP Address',
      'admin.systemLogs.details': 'Details',
      
      // Admin - System Alerts
      'admin.alerts.title': 'System Alerts Configuration',
      'admin.alerts.subtitle': 'Configure system monitoring and notification rules',
      'admin.alerts.createNew': 'Create New Alert',
      'admin.alerts.totalAlerts': 'Total Alerts',
      'admin.alerts.activeAlerts': 'Active',
      'admin.alerts.triggered': 'Triggered Today',
      'admin.alerts.securityAlerts': 'Security Alerts',
      'admin.alerts.noAlerts': 'No alert configurations',
      'admin.alerts.noAlertsDesc': 'Click the button above to create a new alert rule',
      'admin.alerts.threshold': 'Threshold',
      'admin.alerts.recipients': 'Recipients',
      'admin.alerts.lastTriggered': 'Last Triggered',
      'admin.alerts.triggerCount': 'Trigger Count',
      'admin.alerts.notifyList': 'Notification List',
      'admin.alerts.editAlert': 'Edit Alert',
      'admin.alerts.createAlert': 'Create Alert',
      'admin.alerts.comingSoon': 'Feature in Development',
      'admin.alerts.comingSoonDesc': 'Alert creation and editing features coming soon',
      'admin.alerts.confirmDelete': 'Are you sure you want to delete this alert configuration?',
      'admin.alerts.failedLoginAlert': 'Failed Login Alert',
      'admin.alerts.failedLoginDesc': 'Triggered when user consecutive login failures exceed threshold',
      'admin.alerts.systemResourceAlert': 'System Resource Alert',
      'admin.alerts.systemResourceDesc': 'Triggered when system memory usage exceeds 85%',
      'admin.alerts.userSurgeAlert': 'User Registration Surge',
      'admin.alerts.userSurgeDesc': 'Triggered when user registrations exceed 50 per hour',
      'admin.alerts.dbConnectionAlert': 'Database Connection Failed',
      'admin.alerts.dbConnectionDesc': 'Triggered immediately when database connection fails',
      'admin.alerts.suspiciousIPAlert': 'Suspicious IP Activity',
      'admin.alerts.suspiciousIPDesc': 'Triggered when same IP has abnormal requests in short time',
      'admin.alerts.typeSecurity': 'Security',
      'admin.alerts.typeSystem': 'System',
      'admin.alerts.typeUser': 'User',
      'admin.alerts.people': 'people',
      'admin.alerts.times': 'times',
      'admin.alerts.confirmDelete': 'Are you sure you want to delete this alert configuration?',
      
      // Admin - Dashboard
      'admin.dashboard.title': 'Admin Dashboard',
      'admin.dashboard.userManagement': 'User Management',
      'admin.dashboard.serviceCategories': 'Service Categories',
      'admin.dashboard.dataReports': 'Data Reports',
      'admin.dashboard.systemSettings': 'System Settings',
      'admin.dashboard.systemLogs': 'System Logs',
      'admin.dashboard.alerts': 'System Alerts',
      'admin.dashboard.participation': 'Participation Monitoring',
      'admin.dashboard.csrPerformance': 'CSR Performance',
      'admin.dashboard.exportReport': 'Export Report',
      'admin.dashboard.quickActions': 'Quick Actions',
      'admin.dashboard.recentActivity': 'Recent Activity',
      'admin.dashboard.totalUsers': 'Total Users',
      'admin.dashboard.activeRequests': 'Active Requests',
      'admin.dashboard.todayMatches': 'Today\'s Matches',
      'admin.dashboard.pendingReview': 'Pending Review',
      'admin.dashboard.thisMonth': 'this month',
      'admin.dashboard.generateReport': 'Generate Report',
      'admin.dashboard.refreshData': 'Refresh Data',
      'admin.dashboard.noActivity': 'No recent activity',
      'admin.dashboard.reportGenerated': 'Report generated and downloaded!',
      'admin.dashboard.reportError': 'Failed to generate report, please try again later.',
      
      // Admin - User Management
      'admin.users.title': 'User Management',
      'admin.users.subtitle': 'Manage all user accounts in the system',
      'admin.users.totalUsers': 'Total Users',
      'admin.users.users': 'Users',
      'admin.users.searchPlaceholder': 'Search user name or email...',
      'admin.users.allUsers': 'All Users',
      'admin.users.name': 'Name',
      'admin.users.email': 'Email',
      'admin.users.userType': 'User Type',
      'admin.users.status': 'Status',
      'admin.users.requestCount': 'Request Count',
      'admin.users.joinDate': 'Join Date',
      'admin.users.lastLogin': 'Last Login',
      'admin.users.actions': 'Actions',
      'admin.users.active': 'Active',
      'admin.users.suspended': 'Suspended',
      'admin.users.view': 'View',
      'admin.users.suspend': 'Suspend',
      'admin.users.activate': 'Activate',
      'admin.users.delete': 'Delete',
      'admin.users.confirmDelete': 'Are you sure you want to delete this user? This action cannot be undone.',
      'admin.users.confirmDeleteWithRequests': 'This user has {count} related requests. Deleting the user will also delete these requests.',
      'admin.users.deleteSuccess': 'User has been successfully deleted',
      'admin.users.deleteSuccessWithRequests': 'Successfully deleted {userCount} user and {requestCount} related requests',
      'admin.users.noUsers': 'No users found',
      'admin.users.noUsersDesc': 'No users found with current filter criteria',
      'admin.users.userDetails': 'User Details',
      'admin.users.phone': 'Phone',
      'admin.users.address': 'Address',
      'admin.users.emergencyContact': 'Emergency Contact',
      'admin.users.organization': 'Organization',
      'admin.users.skills': 'Skills',
      
      // Login Page
      'auth.login.title': 'Welcome Back',
      'auth.login.subtitle': 'Please login to your account',
      'auth.login.email': 'Email Address',
      'auth.login.password': 'Password',
      'auth.login.userType': 'Select Identity',
      'auth.login.submit': 'Login',
      'auth.login.register': "Don't have an account? Register now",
      'auth.login.noAccount': "Don't have an account?",
      'auth.login.registerNow': 'Register now',
      'auth.login.adminLogin': 'Administrator Login',
      'auth.login.adminLoginDesc': 'You are logging in with an administrator account, no need to select user type',
      'auth.login.error.userType': 'Please select user type',
      'auth.login.error.userNotExists': 'User does not exist, please register first',
      'auth.login.error.userSuspended': 'Your account has been suspended, please contact administrator',
      'auth.register.error.emailExists': 'This email is already registered',
      'auth.register.error.userType': 'Please select user type',
      'auth.register.error.passwordMismatch': 'Password confirmation does not match',
      'auth.register.error.passwordTooShort': 'Password must be at least 6 characters',
      'auth.register.error.requiredFields': 'Please fill in all required fields',
      
      // User Types
      'userType.pin': 'Person in Need (PIN)',
      'userType.pin.description': 'Seeking volunteer assistance',
      'userType.csr': 'Volunteer (CSR)',
      'userType.csr.description': 'Providing volunteer services',
      'userType.admin': 'Platform Administrator',
      'userType.admin.description': 'Managing system operations',
      
      // PIN Dashboard
      'pin.dashboard.title': 'My Dashboard',
      'pin.dashboard.welcome': 'Welcome back, {name}!',
      'pin.dashboard.createRequest': 'Create New Request',
      'pin.dashboard.myRequests': 'My Request List',
      'pin.dashboard.manageRequests': 'Manage all your help requests',
      'pin.dashboard.quickActions': 'Quick Actions',
      'pin.dashboard.viewHistory': 'View History',
      'pin.dashboard.getHelp': 'Get Help',
      'pin.dashboard.noRequests': 'No requests yet',
      'pin.dashboard.noRequestsDesc': 'Post your first help request to find caring volunteers',
      'pin.dashboard.createFirst': 'Post your first help request to find caring volunteers',
      'pin.dashboard.createMyFirst': 'Create My First Request',
      'pin.dashboard.createNew': 'Create New Request',
      'pin.dashboard.help': 'Get Help',
      'pin.dashboard.viewDetails': 'View Details',
      'pin.dashboard.edit': 'Edit',
      'pin.dashboard.delete': 'Delete',
      'pin.dashboard.matchedVolunteer': 'Matched Volunteer: {name}',
      'pin.dashboard.contactVolunteer': 'Click to contact volunteer',
      'pin.dashboard.status.matched': 'Matched',
      'pin.dashboard.status.waiting': 'Waiting',
      'pin.dashboard.status.pending': 'Pending',
      'pin.dashboard.status.processing': 'Processing',
      
      // PIN Dashboard - New Design Translations
      'pin.dashboard.welcomeBack': 'Welcome Back',
      'pin.dashboard.hello': 'Hello',
      'pin.dashboard.heroSubtitle': 'Manage your requests, connect with caring volunteers, and create positive change',
      'pin.dashboard.viewAnalytics': 'View Analytics',
      'pin.dashboard.yourImpact': 'Your Impact',
      'pin.dashboard.impactSubtitle': 'See how your requests help build a better community',
      'pin.dashboard.stat.total.description': 'Total number of requests you\'ve created',
      'pin.dashboard.stat.matched.description': 'Requests successfully matched with volunteers',
      'pin.dashboard.stat.pending.description': 'Requests waiting for volunteer response',
      'pin.dashboard.stat.views.description': 'Total views across all your requests',
      'pin.dashboard.manageYourRequests': 'Manage all your help requests',
      'pin.dashboard.noRequestsYet': 'No requests created yet',
      'pin.dashboard.createFirstRequest': 'Create your first help request to start finding caring volunteers to assist you',
      'pin.dashboard.getStarted': 'Get Started',
      'pin.dashboard.newRequest': 'New Request',
      'pin.dashboard.createNewRequest': 'Create a new help request',
      'pin.dashboard.history': 'History',
      'pin.dashboard.tips': 'Helpful Tips',
      'pin.dashboard.tip1': 'Detailed descriptions help find the most suitable volunteers',
      'pin.dashboard.tip2': 'Adding photos makes your request clearer and more understandable',
      'pin.dashboard.tip3': 'Keep contact information accurate for volunteers to reach you',
      'pin.dashboard.matchedWith': 'Matched with volunteer: {name}',
      'pin.dashboard.contact': 'Contact',
      'pin.dashboard.applicants': 'Applicants',
      'pin.dashboard.interestedVolunteers': 'Interested Volunteers',
      'pin.dashboard.selectVolunteer': 'Select',
      'pin.dashboard.confirmSelect': 'Are you sure you want to select this volunteer?',
      'pin.dashboard.selectSuccess': 'Volunteer matched successfully!',
      'pin.dashboard.complete': 'Complete',
      'pin.dashboard.confirmComplete': 'Confirm this request is completed?',
      'pin.dashboard.completeSuccess': 'Request completed! Thank you for your rating.',
      'pin.dashboard.rateVolunteer': 'Rate Volunteer',
      'pin.dashboard.serviceRating': 'Service Rating',
      'pin.dashboard.feedback': 'Feedback',
      'pin.dashboard.feedbackPlaceholder': 'Share your thoughts about the volunteer service...',
      'pin.dashboard.submitRating': 'Submit Rating',
      'pin.dashboard.filterByStatus': 'Filter by Status',
      'pin.dashboard.sortBy': 'Sort By',
      'pin.dashboard.sort.newest': 'Newest First',
      'pin.dashboard.sort.oldest': 'Oldest First',
      'pin.dashboard.sort.urgent': 'By Urgency',
      'pin.dashboard.showing': 'Showing',
      'pin.dashboard.status.completed': 'Completed',
      'rating.poor': 'Poor',
      'rating.fair': 'Fair',
      'rating.good': 'Good',
      'rating.veryGood': 'Very Good',
      'rating.excellent': 'Excellent',
      'common.optional': 'Optional',
      'common.online': 'Online',
      'common.total': 'Total',
      'common.views': 'Views',
      'common.shortlisted': 'Shortlisted',
      'common.volunteers': 'volunteers',
      'common.new': 'New',
      'common.saved': 'Saved',
      'common.urgent': 'Urgent',
      'common.help': 'Help',
      'common.allCategories': 'All Categories',
      'common.high': 'High',
      'common.medium': 'Medium',
      'common.low': 'Low',
      
      // CSR Dashboard - New Design Translations
      'csr.dashboard.welcomeVolunteer': 'Welcome Volunteer',
      'csr.dashboard.hello': 'Hello',
      'csr.dashboard.heroSubtitle': 'Discover volunteer opportunities, help those in need, and spread kindness',
      'csr.dashboard.exploreRequests': 'Explore Requests',
      'csr.dashboard.myShortlist': 'My Shortlist',
      'csr.dashboard.topVolunteer': 'Top Volunteer',
      'csr.dashboard.thisMonth': 'This Month',
      'csr.dashboard.communityOverview': 'Community Overview',
      'csr.dashboard.overviewSubtitle': 'Understand community needs and find opportunities to help',
      'csr.dashboard.totalRequests': 'Total Requests',
      'csr.dashboard.totalRequestsDesc': 'All pending help requests in the community',
      'csr.dashboard.newToday': 'New Today',
      'csr.dashboard.newTodayDesc': 'Help requests published today',
      'csr.dashboard.shortlistDesc': 'Requests you\'ve followed and saved',
      'csr.dashboard.urgentRequests': 'Urgent Requests',
      'csr.dashboard.urgentDesc': 'Emergency requests needing immediate attention',
      'csr.dashboard.recentRequests': 'Recent Requests',
      'csr.dashboard.latestHelpRequests': 'View the latest published help requests',
      'csr.dashboard.volunteer': 'I Can Help',
      'csr.dashboard.noCategoryRequests': 'No requests in this category',
      'csr.dashboard.tryDifferentCategory': 'Try a different category or check back later',
      'csr.dashboard.noRecentRequests': 'No recent requests',
      'csr.dashboard.checkBackLater': 'Please check back later for new help requests',
      'csr.dashboard.exploreAll': 'Explore All Requests',
      'csr.dashboard.quickActions': 'Quick Actions',
      'csr.dashboard.searchRequests': 'Search Requests',
      'csr.dashboard.findOpportunities': 'Find volunteer opportunities',
      'csr.dashboard.viewShortlist': 'View Shortlist',
      'csr.dashboard.savedRequests': 'Your saved requests',
      'csr.dashboard.myHistory': 'My History',
      'csr.dashboard.pastActivities': 'Past volunteer activities',
      'csr.dashboard.getSupport': 'Get help and support',
      'csr.dashboard.yourImpact': 'Your Impact',
      'csr.dashboard.helpedPeople': 'People Helped',
      'csr.dashboard.hoursVolunteered': 'Hours Volunteered',
      'csr.dashboard.satisfaction': 'Satisfaction',
      'csr.dashboard.impactMessage': 'Thank you for your selfless dedication! Every act of help makes the world a better place.',
      'common.viewDetails': 'View Details',
      
      // PIN History
      'pin.history.title': 'Historical Match Records',
      'pin.history.allServiceTypes': 'All Service Types',
      'pin.history.medical': 'Medical',
      'pin.history.transport': 'Transportation',
      'pin.history.applyFilters': 'Apply Filters',
      
      // Statistics
      'stats.totalRequests': 'Total Requests',
      'stats.matched': 'Matched',
      'stats.pending': 'Pending',
      'stats.totalViews': 'Total Views',
      'stats.availableOpportunities': 'Available Opportunities',
      'stats.urgentRequests': 'Urgent Requests',
      
      // CSR Search Page
      'csr.search.title': 'Search Volunteer Opportunities',
      'csr.search.subtitle': 'Find volunteer service opportunities to help people in need',
      'csr.search.searchPlaceholder': 'Search request title, description or location...',
      'csr.search.allCategories': 'All Categories',
      'csr.search.allUrgency': 'All Urgency Levels',
      'csr.search.opportunities': 'Volunteer Service Opportunities',
      'csr.search.opportunitiesDesc': 'Click "Apply to Volunteer" to help people in need',
      'csr.search.applyVolunteer': 'Apply to Volunteer',
      'csr.search.applied': 'Applied',
      'csr.search.viewDetails': 'View Details',
      'csr.search.noOpportunities': 'No opportunities available',
      'csr.search.noOpportunitiesDesc': 'No pending volunteer service requests at the moment, please check back later',
      'csr.search.noResults': 'No matching results',
      'csr.search.noResultsDesc': 'Try adjusting search criteria or clearing filters',
      'csr.search.clearFilters': 'Clear Filters',
      'csr.search.confirmApply': 'Are you sure you want to apply for this volunteer opportunity?',
      'csr.search.applySuccess': 'Application successful! You can view your volunteer service records in history.',
      'csr.search.loginRequired': 'Please login first before applying for volunteer services!',
      'csr.search.applyError': 'Application failed, please try again!',
      'csr.search.cancelApplication': 'Cancel Application',
      'csr.search.confirmCancel': 'Are you sure you want to cancel this application?',
      'csr.search.cancelSuccess': 'Application cancelled successfully',
      'csr.search.cancelError': 'Failed to cancel application, please try again!',
      'csr.search.rejectRequest': 'Reject Request',
      'csr.search.rejectReason': 'Reason for Rejection',
      'csr.search.rejectReasonPlaceholder': 'Please explain why this request falls outside your responsibility...',
      'csr.search.confirmReject': 'Are you sure you want to reject this request? This will hide it from your search.',
      'csr.search.rejectSuccess': 'Request rejected successfully',
      'csr.search.rejectError': 'Failed to reject request, please try again!',
      'csr.search.shortlist': 'Shortlist',
      'csr.search.shortlisted': 'Shortlisted',
      'csr.search.addToShortlist': 'Added to shortlist',
      'csr.search.removeFromShortlist': 'Removed from shortlist',
      
      // CSR History
      'csr.history.title': 'Volunteer Service History',
      'csr.history.subtitle': 'View your completed volunteer service records and help history',
      'csr.history.totalServices': 'Completed Services',
      'csr.history.serviceTypes': 'Service Types',
      'csr.history.mostActive': 'Most Active',
      'csr.history.filterByType': 'Service Type',
      'csr.history.allServiceTypes': 'All Service Types',
      'csr.history.startDate': 'Start Date',
      'csr.history.endDate': 'End Date',
      'csr.history.clearFilters': 'Clear Filters',
      'csr.history.resultsFound': 'Found {count} service records',
      'csr.history.noRecords': 'No Service Records',
      'csr.history.noRecordsDesc': 'You haven\'t completed any volunteer services yet. Go to the search page to find people in need and start your volunteer journey!',
      'csr.history.noFilteredRecords': 'No Matching Records',
      'csr.history.noFilteredRecordsDesc': 'Try adjusting the filter criteria to view more records',
      'csr.history.browseOpportunities': 'Browse Volunteer Opportunities',
      'csr.history.serviceDate': 'Service Date',
      'csr.history.serviceObject': 'Service Recipient',
      'csr.history.serviceLocation': 'Service Location',
      'csr.history.expectedTime': 'Expected Time',
      'csr.history.contactInfo': 'Contact Information',
      'csr.history.toBeConfirmed': 'To Be Confirmed',
      'csr.history.unknown': 'Unknown',
      
      // CSR Shortlist
      'csr.shortlist.title': 'My Shortlist',
      
      // Help Page
      'help.title': 'Help & Support',
      'help.subtitle': 'Learn how to use the CSR Volunteer Matching System for the best experience',
      
      // PIN User Help
      'help.pin.title': 'Person in Need (PIN) User Guide',
      'help.pin.createRequest.title': 'How to Create a Help Request',
      'help.pin.createRequest.description': 'Post your help request to let volunteers find you',
      'help.pin.createRequest.step1': 'Click the "Create New Request" button',
      'help.pin.createRequest.step2': 'Fill in detailed request information and needs description',
      'help.pin.createRequest.step3': 'Select appropriate service category and urgency level',
      'help.pin.createRequest.step4': 'Submit request and wait for volunteer applications',
      'help.pin.manageRequests.title': 'Manage My Requests',
      'help.pin.manageRequests.description': 'View, edit, and manage all your help requests',
      'help.pin.manageRequests.step1': 'View all request statuses in dashboard',
      'help.pin.manageRequests.step2': 'Click "Edit" to modify request information',
      'help.pin.manageRequests.step3': 'View volunteer applications and contact information',
      
      // CSR User Help
      'help.csr.title': 'Volunteer (CSR) User Guide',
      'help.csr.searchOpportunities.title': 'Search Volunteer Opportunities',
      'help.csr.searchOpportunities.description': 'Find volunteer service opportunities you can participate in',
      'help.csr.searchOpportunities.step1': 'Use search bar and filters to find suitable opportunities',
      'help.csr.searchOpportunities.step2': 'View request details to understand specific needs',
      'help.csr.searchOpportunities.step3': 'Add interesting opportunities to your shortlist',
      'help.csr.applyVolunteer.title': 'Apply for Volunteer Service',
      'help.csr.applyVolunteer.description': 'Apply to participate in volunteer service and connect with people in need',
      'help.csr.applyVolunteer.step1': 'Click the "Apply to Volunteer" button',
      'help.csr.applyVolunteer.step2': 'Confirm application information and submit',
      'help.csr.applyVolunteer.step3': 'Wait for successful matching then contact the help seeker',
      
      // Admin Help
      'help.admin.title': 'Administrator User Guide',
      'help.admin.categoryManagement.title': 'Manage Service Categories',
      'help.admin.categoryManagement.description': 'Add, edit, and delete service categories in the system',
      'help.admin.categoryManagement.step1': 'View existing categories in category management page',
      'help.admin.categoryManagement.step2': 'Add new service categories',
      'help.admin.categoryManagement.step3': 'Delete categories that are no longer needed',
      'help.admin.reports.title': 'View Data Reports',
      'help.admin.reports.description': 'Generate and view system usage statistics reports',
      'help.admin.reports.step1': 'Select report type (daily, weekly, monthly)',
      'help.admin.reports.step2': 'Click generate report button',
      'help.admin.reports.step3': 'Analyze user activity and matching data',
      
      // FAQ
      'help.faq.title': 'Frequently Asked Questions',
      'help.faq.q1.question': 'How to create an effective help request?',
      'help.faq.q1.answer': 'Please describe your needs in detail, including specific time, location, and expected type of help. Clear descriptions help volunteers better understand your needs.',
      'help.faq.q2.question': 'How long does it take to get a response after a volunteer applies?',
      'help.faq.q2.answer': 'Usually within 24 hours, the help seeker will review volunteer applications and respond. The system will automatically send notification reminders.',
      'help.faq.q3.question': 'How to modify a published request?',
      'help.faq.q3.answer': 'Find the corresponding request in your dashboard and click the "Edit" button to modify request information. Note: Modifying matched requests may affect volunteers.',
      'help.faq.q4.question': 'Does the system charge fees?',
      'help.faq.q4.answer': 'The CSR Volunteer Matching System is completely free. We are committed to providing a free volunteer service matching platform for the community.',
      
      // Contact Us
      'help.contact.title': 'Contact Us',
      'help.contact.support.title': 'Technical Support',
      'help.contact.support.description': 'Encountering technical issues or need help using the system?',
      'help.contact.support.hours': 'Monday to Friday 9:00-18:00',
      'help.contact.feedback.title': 'Feedback',
      'help.contact.feedback.description': 'Your suggestions are important to us',
      'help.contact.feedback.form': 'Online Feedback Form',
      
      // Categories
      'category.medical': 'Medical Companion',
      'category.transportation': 'Transportation',
      'category.shopping': 'Shopping Assistance',
      'category.household': 'Household Help',
      'category.companion': 'Companion Service',
      'category.technology': 'Tech Support',
      'category.education': 'Educational Tutoring',
      'category.other': 'Other',
      
      // Urgency
      'urgency.low': 'Low',
      'urgency.medium': 'Medium',
      'urgency.high': 'High',
      'urgency.urgent': 'Urgent',
      
      // Status
      'status.pending': 'Pending',
      'status.matched': 'Matched',
      'status.completed': 'Completed',
      'status.cancelled': 'Cancelled',
      
      // Request Form
      'request.form.title': 'Request Title',
      'request.form.category': 'Service Type',
      'request.form.description': 'Detailed Description',
      'request.form.location': 'Location',
      'request.form.urgency': 'Urgency Level',
      'request.form.expectedDate': 'Expected Date',
      'request.form.expectedTime': 'Expected Time',
      'request.form.volunteersNeeded': 'Number of Volunteers Needed',
      'request.form.contactMethod': 'Contact Method',
      'request.form.additionalNotes': 'Additional Notes',
      'request.form.attachments': 'Attachments (optional)',
      'request.form.attachmentsHint': 'Supports images, PDF, DOC/DOCX. Max per-file size 5MB',
  'contact.phone': 'Phone',
  'contact.email': 'Email',
  'contact.both': 'Phone and Email',
      'request.form.create': 'Create New Help Request',
      'request.form.edit': 'Edit Help Request',
      'request.form.update': 'Update Request',
  'request.form.titlePlaceholder': 'Use at least 5 characters to briefly describe your need',
  'request.validation.titleMinHint': 'min 5 chars',
  'request.validation.descriptionMinHint': 'min 10 chars',
  'request.form.descriptionPlaceholder': 'Use at least 10 characters to describe your need in detail, including specific requirements and notes',
  'request.form.locationPlaceholder': 'Detailed address or area',
  'request.form.additionalNotesPlaceholder': 'Any additional information...',
  'request.form.submitting': 'Publishing...',
  'request.section.basicInfo': 'Basic Information',
  'request.section.timing': 'Timing & Other Requirements',
      
      // Request Details
      'request.detail.title': 'Request Details',
      'request.detail.basicInfo': 'Basic Information',
      'request.detail.description': 'Detailed Description',
      'request.detail.timing': 'Timing Information',
      'request.detail.requester': 'Requester Information',
      'request.detail.statistics': 'Statistics',
      'request.detail.volunteer': 'Volunteer Information',
      'request.detail.createdAt': 'Created At',
      'request.detail.expectedTiming': 'Expected Time',
  'request.rating.leaveRatingFor': 'Leave a rating for {name}',
  'request.rating.select': 'Select rating',
  'request.rating.submit': 'Submit Rating',
  'request.rating.feedbackPlaceholder': 'Optional: leave a comment for the volunteer',
  'error.submitRating': 'Failed to submit rating, please try again',
  'error.updateRequestFailed': 'Failed to update request',
  'error.deleteRequestFailed': 'Failed to delete request',
  'error.selectVolunteerFailed': 'Failed to select volunteer, please try again',
  'error.completeRequestFailed': 'Failed to complete request, please try again',
      'request.detail.viewCount': 'View Count',
      'request.detail.shortlistCount': 'Shortlist Count',
      'request.detail.matchedAt': 'Matched At',
      'request.detail.noVolunteer': 'No volunteer matched yet',
      
      // Time
      'time.justNow': 'Just now',
      'time.hoursAgo': '{count} hours ago',
      'time.daysAgo': '{count} days ago',
      'time.weeksAgo': '{count} weeks ago',
    }
  };
  
  return translations[language] || translations.zh;
};